  export enum TYPES { SERVANT, CE }
  export enum CLASSES { SHIELDER, SABER, LANCER, ARCHER, RIDER, CASTER, ASSASSIN, BERSERKER, RULER, ALL, AVENGER, ALTER_EGO = 13, MOON_CANCER = 14, FOREIGNER = 16 }